add_newline = false

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[package]
disabled = true

[os]
format = '[$symbol](big fg:red) '   
disabled = false

[os.symbols]
Fedora = ''

[directory]
truncation_length = 0
home_symbol = ''
style = "fg:white"
read_only_style = '197'
read_only = '  '

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
disabled = true
